### ISSUE TITLE
Unable to close floating dialog when saving elm file with syntax errors

### ISSUE THREAD

**Issue by martisj** [nvim-lua/kickstart.nvim#1033]
## Describe the bug

I've got this elm file:
```elm
myDef: String
myDef = "Hello"

error in my func
0.0
```
When I save `:w` I see this dialog
![image](https://github.com/user-attachments/assets/2ea9b637-a7f3-4c80-8f05-041a249eea26)
I can't close it with `q` or navigate to it with `<C-w>w`.
What does make it go away is opening a Telescope picker, like "Workspace Diagnostics" (`<leader>sd`)
## To Reproduce

1. Load the elm code from above:
    ```elm
    myDef: String
    myDef = "Hello"
    
    error in my func
    0.0
    ```
2. Think you need `elmls` and `elm-format` installed.
3. Save the flie `:w`
4. The dialog should open, and not be focusable or closable.

_Extra infoz_
![image](https://github.com/user-attachments/assets/509bf2df-a022-4b4e-b0ba-81919ac61509)
If I do `:wq` I get this message

## Desktop

- OS: OpenSUSE Tumbleweed 20240714
- Terminal: Alacritty, fish shell
- Tmux 3.4 and regular non-tmux produces the same result
- Kernel: Linux 6.9.9-1-default

## Neovim Version

NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run ":verbose version" for more info.0

**Comment by VlaDexa** [comment]
## So, what have I found after some digging: 
- When you get "No write since last change for buffer "[Prompt]"" you can close that telescope window by using ":q!", but be careful because it doesn't always close telescope window and may close the buffer without saving your changes (I haven't found why this behavior exists).
- When you use `<leader>f` or `:lua vim.lsp.buf.format()` it correctly focuses on the error window, so you can close it.
- This is looks like elm_format issue because it's reporting a strange error code that neither conform nor `vim.lsp.buf.format` recognize. I say this because this doesn't happen with formatters for other languages which also error on syntax errors but don't open any floats.

## Temporary solution:
Silence all errors from elm_format in conform.nvim opts. 
### Mini example:
```lua
  {
    'stevearc/conform.nvim',
    opts = {
      formatters_by_ft = {
        elm = { 'elm_format', quiet = true }, 
      }
    }
  }
```
I should mention that this works only on *very* recent conform.nvim version and isn't even in any stable version, as far as I know. Kickstart by default uses the latest commit of conform, so if you didn't change that, you can pull latest version in Lazy. 
## What probably should be done
You can open an issue in [elm_format](https://github.com/avh4/elm-format) mentioning something from this response or try fixing it yourself and open a PR.

**Comment by feoh** [comment]
Is this really a kickstart issue or more a Telescope/elm LSP issue?

**Comment by VlaDexa** [comment]
The only way I see to fix it from kickstart is to add configuration for elm formatter. But it's more of a silencing than a fix

**Comment by feoh** [comment]
OK thanks. Please report this issue to whatever LSP or formatter elm uses :)
