### ISSUE TITLE
Shell files not being detected by mason or lsp

### ISSUE THREAD

**Issue by jpringle1** [nvim-lua/kickstart.nvim#1089]
## Describe the bug
When i open a .sh script with nvim using the config and plugins provided in this repo, bash-language-server is not automatically activated, so i get no warnings or errors in the script.

Even after manually installing bash-language-server with Mason, no analysing occurs.

## To Reproduce
1. Setup kickstart.nvim
2. open a .sh script
3. Run :Mason to see if bash-language-server is automatically installed and running

## Desktop
- OS: OpenSuse Tumbleweed
- Terminal: Wezterm

## Neovim Version
```
v0.10.0
```

**Comment by byrmsh** [comment]
> When i open a .sh script with nvim using the config and plugins provided in this repo, bash-language-server is not automatically activated, so i get no warnings or errors in the script.

`bash-language-server` doesn't actually provide linting by itself but instead requires `shellcheck` to be installed alongside as can be read from their [README page](https://github.com/bash-lsp/bash-language-server/blob/4353aaba4e0117c0f35965a003343ebaa43ccbd6/README.md?plain=1#L28-L31):

> As a dependency, we recommend that you first install [shellcheck](https://www.shellcheck.net/) to enable linting: https://github.com/koalaman/shellcheck#installing . If shellcheck is installed, bash-language-server will automatically call it to provide linting and code analysis each time the file is updated (with debounce time of 500ms).

This is probably a simple misunderstanding as I have no issues with bash-language-server for LSP in a clean kickstart.nvim setup after following the exact steps you listed.

For future-reference, it is a good idea to check `:LspInfo` to see if the client is attached to the current buffer instead of only checking if any code errors/warnings are shown.
