### ISSUE TITLE
No autocompletion for C files

### ISSUE THREAD

**Issue by mbert** [nvim-lua/kickstart.nvim#111]
I am running `nvim` installed from homebrew on a Mac. Installed your `init.lua` file, saw how stuff initialised, restarted nvim, opened a C file. The screen looks like in your video ("Effective Neovim: Instant IDE"). However there is no autocomplete, and shortcuts like `gr` do not work. When opening `~/.config/nvim/init.lua` in `nvim`, autocomplete works like in the video. 

Are there any particularities I need to consider on a Mac? I have removed the files installed by `init.lua` several times and rerun the bootstrap process, no change.

**Comment by emanuxd11** [comment]
Same issue here on arch linux

**Comment by mbert** [comment]
Thank you, hence it's not only on MacOS. Changed the title accordingly.

**Comment by prscoelho** [comment]
Did you install the c lsp? What does :LspInfo show?

**Comment by mbert** [comment]
> Did you install the c lsp? 

I only installed the `init.lua` file (as there was nothing else mentioned in the documentation).

> What does :LspInfo show?

<img width="637" alt="Screenshot 2023-01-01 at 23 18 05" src="https://user-images.githubusercontent.com/383271/210186165-ff3ffd3d-6f63-4dd0-9a07-f0db192b72ec.png">

As it lists only `sumneko_lua`, this indicates that I need to install support for more programming languages manually?
In that case mentioning this information in the video and adding it to the README would probably be a good idea.
How do I - a complete newbie - set `nvim` up for other programming languages? Which are available?

**Comment by prscoelho** [comment]
In the init.lua you can uncomment [this line](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L340) to install and enable clangd, I think that's the lsp you're looking for. Alternatively, you can run `:Mason` and it will list all the available lsps. You can use the interface that shows up to install anything on that list, instructions [here](https://github.com/williamboman/mason.nvim)

As for tree-sitter syntax highlighting, c is already included in the `ensure_installed` list, but for other languages that aren't you would add those there.

**Comment by mbert** [comment]
Thank you, that was missing. Having played around with them a bit, it looks like most of the language servers require additional software to be installed? At least not all of them seem to be set up by just adding a single line?

**Comment by downhiller** [comment]
I'm struggling as well... complete vim LSP/IDE noob - I'd never even heard of LSP before today.  Same as @mbert, my :LspInfo showed nothing, but I've since installed phpactor to my project root and then installed that via :Mason.  :LspInfo now shows 

![image](https://user-images.githubusercontent.com/6060913/210375951-44052fd3-0e02-48d9-96f0-3031a19b1ec2.png)

But I still don't get any autocompletion jazziness when I start typing.  What else should I check / might I be missing?

Thank you!

**Comment by downhiller** [comment]
Is it because I don't have node/npm installed?  Are they requirements for Mason to work?  If so the github page for mason doesn't seem to mention that, but I'm very aware that the pertinent lines here say "ERROR", rather than "WARNING"L:

![image](https://user-images.githubusercontent.com/6060913/210376970-c7e96801-a6f7-4b6e-853d-b042c41eeb7b.png)

**Comment by tjdevries** [comment]
I'm going to close now -- let me know if you can't get this to work in the latest version of kickstart (using new package manager and set up)
