### ISSUE TITLE
The defer clipboard is making it impossible to yank/copy to system clipboard

### ISSUE THREAD

**Issue by tagptroll1** [nvim-lua/kickstart.nvim#1121]
## Describe the bug
With the defer clipboard=unnamedplus change done in https://github.com/nvim-lua/kickstart.nvim/commit/84cc12354dbe0ebda180d445f54820def8c4638f 
I am now unable to yank to system clipboard. Any combo of just yanking, and yanking to `*` and `+` register does nothing. 
Simply removing the `vim.schedule(function()` part of the clipboard setup fixed my issues. 

## To Reproduce
1. Open nvim
2. Write something
3. yy / `"+yy` / `"*yy` 
4. paste anywhere else outside the terminal
5. Nothing is stored

## Desktop
- OS: PopOs 24.04 With Cosmic DE / wayland
- Terminal: Cosmic-term

## Neovim Version
```
NVIM v0.11.0-dev-621+g172cc23d8
Build type: RelWithDebInfo
LuaJIT 2.1.1723675123
```
But also re-producable with LTS v0.10

**Comment by abeldekat** [comment]
That's suprising. A similar change is also present in LazyVim and AstroNvim. My first guess would be that the problem is `wayland` related, although I do expect that LazyVim and AstroNvim also have `wayland` users.

Just to be sure, can you verify that the problem occurs using version `v0.10.1` when following these steps:

```sh
cd ~/.config
git clone https://github.com/nvim-lua/kickstart.nvim.git repro
cd ~/.config/repro
NVIM_APPNAME=repro nvim init.lua
```

Steps to remove:
```sh
rm -rf ~/.config/repro
rm -rf ~/.local/share/repro
rm -rf ~/.local/state/repro
rm -rf ~/.cache/repro
```

**Comment by abeldekat** [comment]
`PopOs 24.04 With Cosmic DE / wayland` is currently in the [alpha](https://system76.com/cosmic) phase:

> ... Try COSMIC Epoch 1 (alpha 1) on the Pop!_OS 24.04 LTS alpha.

I could not install the OS in `virtualbox`. I did install `PopOs 22.04`. That worked, but has no `wayland`.

I installed `ubuntu 24.04` in virtualbox. The default session is `wayland`. Using neovim's stable `appimage`, I also installed `ripgrep` and `wl-clipboard`. Running default `kickstart`, I was able to yank to the clipboard. The provider is `wl-copy`.

**Comment by abeldekat** [comment]
I installed `cosmic` on top of `pop os 22.04` on a virtual machine, using [this](https://www.linuxfordevices.com/tutorials/install-cosmic-desktop) article.

I could not reproduce the issue.

`:checkhealth`:

> OK Clipboard tool found: wl-copy

**Comment by tagptroll1** [comment]
I'll do my best to help reproduce it. I'll get to it after work today 
possibly. (GMT+2 time)

**Comment by tagptroll1** [comment]
I've narrowed it down to the clipboard only working if I open a file. (Like .config/nvim/init.lua). If i simply open `nvim` on root and start typing, then I cannot yank any of the text to clipboard. That gives `clipboard: No provider. Try ":checkhealth"` 
Navigating to a file from there seems to do it, most of my tests have been around just opening nvim and trying to yank anything i write there.

**Comment by abeldekat** [comment]
Hello @tagptroll1,

I still cannot reproduce on `popos 22.04` with `cosmic` in a virtual machine. Just to be sure: Did you test with the steps I provided [here](https://github.com/nvim-lua/kickstart.nvim/issues/1121#issuecomment-2327339759). Otherwise, could you share your config?

My tests:

- `nvim` without arguments, directory is `~/.config/nvim`. Type some text. Yank is working. `:checkhealth` reports `wl-copy` as `provider.clipboard`.
- `nvim init.lua`, directory is `~/.config/nvim`. Yank some text. Yank is working.`:checkhealth` reports `wl-copy` as `provider.clipboard`.

When I uninstall `wl-clipboard`, I get the message you are referring to in both cases, which is to be expected:

> clipboard: No provider. Try ":checkhealth"

If I also remove the `vim.schedule`, the same happens in both cases:

> clipboard: No provider. Try ":checkhealth"

**Comment by abeldekat** [comment]
I managed to install `popos 24.04 cosmic` in a virtual machine, using the `intel/amd` [iso](https://system76.com/cosmic).

I installed the appimage for [neovim stable](https://github.com/neovim/neovim/blob/master/INSTALL.md#appimage-universal-linux-package), `ripgrep` and `wl-clipboard`.

Using stock kickstart, I can copy to the clipboard without problems.

**Comment by tagptroll1** [comment]
> * `nvim` without arguments, directory is `~/.config/nvim`.

Yes. I followed the steps there, closed the init file and ran `NVIM_APPNAME=repro nvim`. Wrote yayayay, and `V + y` to yank the line. My clipboard now still contains `NVIM_APPNAME=repro nvim` 
I get No provider in the error, but when i checkhealth I see
```
Clipboard (optional) ~
- OK Clipboard tool found: wl-copy
```
But now the clipboard works when I go back to the original buffer of `yayaay` and copy that.

**Comment by abeldekat** [comment]
Thanks for your patience!

I have a hard time understanding the problem. The `schedule` should run without any conditions, even before `lazy.nvim` starts loading plugins on `VeryLazy`.
It's really strange that the clipboard starts working when you go back "to the original buffer".

As I still cannot reproduce, I hope you'll allow me some extra questions.

1 Could you add a `vim.print("1 ***********************")` and a `vim.print("2 ********************")` before and after the line that sets the option inside the `schedule` function? Are these lines printed when you start `nvim`, even before you start typing?
2. Could you do a `:checkhealth` before you start typing? Is the provider found?

We both run `cosmic` and use stock `kickstart`. How did you install `nvim`?

**Comment by tagptroll1** [comment]
Adding these prints I get the following prints when i open `nvim` without doing anything. I never see the 2 print.
```
vim.print '1 before schedule **********'
vim.schedule(function()
  vim.print '2 inside schedule **********'
  vim.opt.clipboard = 'unnamedplus'
  vim.print '3 inside after setting **********'
end)
vim.print '4 after schedule **********'
```

```
1 before schedule ********
4 after schedule ********
``` 
After pressing enter on the first print I get
``` 
3 inside after setting ********
``` 

Opening nvim and immediately doing `:checkhealth` without even entering insert mode shows
``` 
Clipboard (optional) ~
- OK Clipboard tool found: wl-copy
``` 
(With the clipboard working, as i copied that from the health buffer)

**Comment by abeldekat** [comment]
Thanks!

> ... After pressing enter on the first print I get

I unfortunately don't understand what you mean by pressing enter on the first print. I would expect prints '1' and '4' to occur immediately. Is print '3' only shown when you press `enter` while in normal mode in the empty buffer?

How did you install Neovim? As the `nvim` version in `cosmic` is too old, I installed the `stable appimage`, version `10.1`

Also: In your terminal, what is the output of:

``` sh
wl-copy -v
```
I get: 

```text
wl-clipboard 2.2.1
```

**Comment by tagptroll1** [comment]
Pressing enter was my natural response to seeing the prints at the bottom, as if they were popups i had to close. So yeah, Enter in normal mode is probably right. 
wl-copy -v gives 2.2.1

I installed nvim from tarball, downloading latest pre-release (and tried with 10.1)
```
    Download nvim-linux64.tar.gz
    Extract: tar xzvf nvim-linux64.tar.gz
    Run ./nvim-linux64/bin/nvim
``` 
With a small PATH statement in zshrc. 
I use zsh btw, if that changes anything.

**Comment by abeldekat** [comment]
> I installed nvim from tarball, downloading latest pre-release (and tried with 10.1)

I would be very curious to know if the problem also occurs when you use the `appimage`. You could comment out that path statement in `.zshrc` to disable the `tarball` installation. The instructions for the `appimage` can be found [here](https://github.com/neovim/neovim/blob/master/INSTALL.md#appimage-universal-linux-package).

> curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage

EDIT:

I think the best approach is to `sudo mv` the `appimage` to `/opt/nvim/nvim`. When you add `/opt/nvim/` to your path you can use the `nvim` command.
Please also remove your local installation in order to start from scratch:

```sh
rm -rf ~/.local/share/repro
rm -rf ~/.local/state/repro
rm -rf ~/.cache/repro
```

**Comment by tagptroll1** [comment]
Ok to list my steps, I renamed my .config/nvim to .config/nvimm. I moved my /opt/nvim/ to /opt/nvimm (My path points to /opt/nvim/bin, which wont hit now) 
I downloaded the appimage, gave it exec, moved it to /opt/nvim/nvim and added /opt/nvim to path. 

Currently yanking to + registry works, there is no config atm. (`"+y`) 
Installing Kickstarts config with previously mentioned steps
```
cd ~/.config
git clone https://github.com/nvim-lua/kickstart.nvim.git repro
``` 

and running nvim with no files
```
NVIM_APPNAME=repro nvim
```

With the exact keystrokes: `ihello<Ctrl+c>Vy` 
I get Clipboard: No provider, and hello is **not** in my clipboard.
`:checkhealth` says its all good, and after checking health I was able to yank the hello with the same keystrokes. (without closing nvim)

**Comment by dam9000** [comment]
@tagptroll1 with the steps you now provided I can reproduce the issue as well:

![image](https://github.com/user-attachments/assets/0e2a40b6-6798-4dee-a8a5-29acc7a2562c)

This is with X (not wayland) and the clipboard is:
```
Clipboard (optional) ~
- OK Clipboard tool found: xsel
```

if I comment out the `schedule()` it works fine.

**Comment by abeldekat** [comment]
@tagptroll1 

That's a really good reproducible scenario. Thank you for persisting!

I can also reproduce(arch + xsel).

Note that the clipboard is found when the scenario is changed slightly:

`ihello<esc>Vy`

Also, in my personal config, I cannot reproduce, probably because I use a dashboard. When I disable the dashboard, the erroneous behavior is present. That also explains why the issue is not reported for `LazyVim` and `Astronvim`: Those distros also use a dashboard plugin.

I think you found an "edge case" that occurs given the following restrictions:

1. The config does not have a `starter` plugin, but uses `intro` directly
2. User presses `ihello<ctrl-c>Vj` instead of `ihello<esc>Vj`
3. User did not do anything else before `step 2`. For example: First press `enter`, or `h`

Big question: Why?

EDIT: To restrict the scenario even more, I remember your `enter` remark in one of the previous comments, and added a third bullet point above.

**Comment by tagptroll1** [comment]
Why I press ctrl-c or why does it happen? :D 
answer to both is I dont know.

**Comment by abeldekat** [comment]
I added a third restriction in [this](https://github.com/nvim-lua/kickstart.nvim/issues/1121#issuecomment-2339878867) comment.

First guess: It is related to some difference between `<ctrl-c>` and `<esc>`. Also, *perhaps* this edge case is not only relevant to the `clipboard schedule`. 

Need to investigate.

**Comment by abeldekat** [comment]
:h ctrl-c:

i_CTRL-C
CTRL-C		Quit insert mode, go back to Normal mode.  Do not check for
		abbreviations.  Does not trigger the InsertLeave autocommand
		event.

**Comment by abeldekat** [comment]
~~Given this scenario:~~

~~1. Config does not have a `starter` plugin. When `nvim` is openend, `intro` is displayed
2. The user types `ihello<ctrl-c>Vy`~~

~~Result:~~

~~> clipboard: No provider. Try ":checkhealth" or ":h clipboard"~~

~~I consider this an edge case that only happens when:~~

~~1. The clipboard option is scheduled
2. `<ctrl-c>` is used instead of `<esc>`
3. User edits inside `intro` and enters the sequence exactly as described. For example, if the user first presses `enter`(or something else, like `h`), yanking works as expected. This is also the case on `:enew`.~~

~~Perhaps the fact that `i_CTRL_C` does not trigger the `InsertLeave autocommand` is relevant.~~ 

@dam9000, @feoh, what do you think? Shall I create a `neovim` issue?

**Comment by abeldekat** [comment]
I have to retract the [previous](https://github.com/nvim-lua/kickstart.nvim/issues/1121#issuecomment-2340021447) comment. It is not an edge case because it also happens when the user starts nvim with an argument. 
I can reproduce using stock `LazyVim`:

1. nvim `init.lua`
2. type: `ihello<ctrl-c>Vy`

Still valid:

1. The clipboard option is scheduled
2. `<ctrl-c>` is used instead of `<esc>`
3. User enters the sequence exactly as described. For example, if the user first presses `enter`(or something else, like `h`), yanking works as expected. This is also the case on `:enew`.

Perhaps the fact that `i_CTRL_C` does not trigger the InsertLeave autocommand is relevant.

Note: I tested whether the clipboard instruction is set:

```lua
vim.schedule(function()
  vim.opt.clipboard = 'unnamedplus'
  vim.print 'DONE'
end)
```
Done is printed, also when yanking results in an error:

> clipboard: No provider. Try ":checkhealth" or ":h clipboard"

**Comment by abeldekat** [comment]
Very relevant:

https://github.com/neovim/neovim/pull/29581#issuecomment-2318966355

> Users need to understand that ctrl-c from insert mode skips various features. That's intentional.

**Comment by tagptroll1** [comment]
Huh, oh well! I guess that solves the mystery at least

**Comment by abeldekat** [comment]
> Huh, oh well! I guess that solves the mystery at least

Indeed....;)

I think this issue is mostly about using `i_Ctrl_C` and the related [side-effects](https://github.com/neovim/neovim/pull/29581#issuecomment-2318966355).

Perhaps its best to use `<esc>` instead of `i_Ctrl_C`. Another possibility, described [here](https://github.com/neovim/neovim/issues/28516#issuecomment-2211690872) and [here](https://github.com/LazyVim/LazyVim/issues/3569#issuecomment-2212335199) is to remap `<ctrl-c>` to `<esc>`.  However, as the `i_Ctrl_C` behavior is by design, I don't know if that approach has any disadvantages. **EDIT**: I found [this](https://github.com/neovim/neovim/issues/16416#issuecomment-1509759646) comment.

Your fix, removing the `vim.schedule` inside your config, is also an option.

Thanks @dpetka2001, for finding that `neovim` issue!

**Comment by feoh** [comment]
I would rather not make this change as it's one platform only, unless folks like @dam9000 feel it's really truly necessary. Based on @abeldekat's excellent synopsis above it seems like there are other options for you to explore?

**Comment by abeldekat** [comment]
@feoh,

I know that I have been focussing on the platform in the beginning of his issue. However, this can [happen](https://github.com/nvim-lua/kickstart.nvim/issues/1121#issuecomment-2340089387) on all platforms, and can also be reproduced in `LazyVim`.

As [mentioned](https://github.com/nvim-lua/kickstart.nvim/issues/1121#issuecomment-2341564872) here, I think the advice should be: Don't use `i_ctr_c` as a substitute for `<esc>`. There are many caveats. If the user insists on using `i_ctrl_c` in that way, the user should remove the `schedule` from the config. It's also possible to remap `i_ctrl_c` onto `<esc>`.  That's not [advisable](https://github.com/neovim/neovim/issues/16416#issuecomment-1509759646) though.

**Comment by dpetka2001** [comment]
However you can map it to `<C-c>` as per the [advice of this dev](https://github.com/neovim/neovim/issues/16416#issuecomment-1509762488). I tested it and it doesn't break command history or closing Telescope window with `<c-c>`. And it also does not have the problem with the clipboard provider. Others should test it as well to confirm. `vim.keymap.set('i', '<C-c>', '<C-c>')`

**Comment by abeldekat** [comment]
Thanks @dpetka2001! I saw that too, but did not test it. Mostly because that comment has four "confused" emojis attached to it....;)

**Comment by dpetka2001** [comment]
@abeldekat I don't trust emojis since it can be just because of people tendency to not have their own way. I just test things. Of course I only tested these 3 situations and there might be some other cases still undiscovered. Only those who will use this mapping will be able to tell. Would appreciate if you could also confirm and other users as well.

@feoh 

The bottom line is there's nothing wrong with the defer clipboard implementation. I'm just a simple LazyVim user expressing just my personal opinion. It's up to the maintainers of this repo to include this improvement or not (I would personally include it in my personal configuration even if LazyVim didn't adopt it). 

The problem is entirely with the users' usage of `<C-c>` as a substitute for `<esc>`. Users should be discouraged from using it in my personal opinion. There was even an issue where it could cause Neovim to hang with 100% cpu usage on rare occasions, but that has been reportedly solved. Still there are other edge issues as well. If users want to use it no matter what, I believe they should make appropriate changes in their personal configuration. It's generally not considered best practice for users to use `<C-c>` from what I've read across Github Neovim ecosystem. 

Just my 2 cents. Keep doing what you do best everyone :smile:

**Comment by abeldekat** [comment]
I tested the mapping you suggested and it works fine. Your 2 cents are very valuable... Thank you!

**Comment by dam9000** [comment]
You're wading in black magic territory here :smile: 
Mapping ctrl-c to ctrl-c because schedule clipboard messes things up, which is there to gain minor startup milliseconds?
This sounds silly. :stuck_out_tongue_winking_eye: 
I would just remove the schedule clipboard and forget about it. I think the slow clipboard startup on some platforms is an issue that should be solved in core neovim not in various config distros. But that's just IMHO. Btw, has anyone raised the slow clipboard startup issue to core neovim?

**Comment by dpetka2001** [comment]
It's not schedule clipboard that messes things up. It's the usage of `<C-c>` that messes things up because it skips certain procedure steps (like for example not invoking the `InsertLeave` autocmd event for example) as already mentioned by Neovim developers themselves.

**Comment by feoh** [comment]
OK.Thank you for the report, I don't see any actual work for us here. Pull requests are, as always, welcome so please feel free to author one and do the appropriate testing for all our platforms (Linux, Mac, Windows mostly) and we'll definitely give it all due consideration.

Closing this for now.

**Comment by michaeldebetaz** [comment]
Hi everyone! I don't know if my comment is useful here, but maybe it can show some light. I am using neovim 0.10.0 on Ubuntu 24.04.1 (WSL) and the following code doesn't link the neovim clipboard to the system clipboard.
```lua
-- Sync clipboard between OS and Neovim.
--  Remove this option if you want your OS clipboard to remain independent.
--  See `:help 'clipboard'`
vim.schedule(function()
	if vim.fn.has("wsl") == 1 then
		vim.opt.clipboard = {
			name = "WslClipboard",
			copy = {
				["+"] = "clip.exe",
				["*"] = "clip.exe",
			},
			paste = {
				["+"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
				["*"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
			},
			cache_enabled = 0,
		}
	else
		vim.opt.clipboard = "unnamedplus"
	end
end)
```
However, using `vim.g.clipboard` instead of `vim.opt.clipboard` (like it was in the previous kickstart configs) works.
