### ISSUE TITLE
[Question] “Remap for dealing with word wrap”?

### ISSUE THREAD

**Issue by fooness** [nvim-lua/kickstart.nvim#114]
Hello everyone,

please excuse me filling a “Bug report” as I think there’s neither a question template nor the discussions are activated.

I would like to ask a probably rather simple question, but I cannot figure out the answer; it’s also not in the kickstart.nvim video.

What does do [“Remap for dealing with word wrap”](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L139-L141) do?

```
-- Remap for dealing with word wrap
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
```

Thank you very much for all of your hard work for the neovim community and ecosystem!

**Comment by seantwie03** [comment]
It is often better to get information directly from the source. One good source is often the help pages.

```
:h v:count
:h gk
:h gj
```

Many vim motions can be preceded with a count. For example, if you press 5j you will go down 5 lines. This code is saying, if no count was passed in, perform gj/gk else perform k/j.  

So, if you are on a wrapped line and you presss j, this mapping will enter 'gj' taking you down one 'display line'. However, if you are on a wrapped line and you press 5j this mapping will take you down 5 'real' lines. This makes sense because if you use relative line numbers, they count real lines not display lines.

**Comment by fooness** [comment]
Thank you very much for taking the time to explain.

Thinking about wrapped lines, this definitely makes sense now!
