### ISSUE TITLE
Github Copilot plugin is not installing

### ISSUE THREAD

**Issue by haseeb-heaven** [nvim-lua/kickstart.nvim#184]
**Describe the bug**
The Github co-pilot plugin is not installing when using **LUA** based configuration.

**To Reproduce**
1. Setup "init.lua" config from this Repo.
2. Go to [Copilot Repo - VIM](https://github.com/github/copilot.vim)
3. Now install it.
4. Now open Neovim editor enter command mode and type _:Copilot setup_
5. See the error **Copilot setup Command not found**.

**Desktop (please complete the following information):**
- OS: MacOS.
- Terminal: ZSH,iTerm.

** Neovim Version **
 - Output of running `:version` from inside of neovim:
:version
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```
```
```

**Comment by Xanthus58** [comment]
I'm having this exact issue across all of the devices I've tested it with. (3x Linux 1x windows) 

Same setup as this user but instead I use alacrity and fish.

**Comment by Xanthus58** [comment]
Note to user @haseeb-heaven i'm not 100% sure on this so someone correct me if i'm wrong. But i belive the reason that the method didnt work for both of us is due to the fact that kickstart uses the lazy plugin manager. 

I was able to get copilot working on all my machines by going into my init.lua file and going to any location within the "require('lazy').setup({" bracket. And entering "'github/copilot.vim'," Heres a screenshot for reference.
![image](https://user-images.githubusercontent.com/66909997/219966405-c74d1ad5-d2a3-43f9-809b-0d9e07940ce4.png)

Try it out and see if the method works for you too.

**Comment by haseeb-heaven** [comment]
@Xanthus58 Thanks i will try and let you know.

**Comment by haseeb-heaven** [comment]
Solution mentioned by @Xanthus58 fixed this issue.

**Comment by alexbaikal** [comment]
Does it show prompts to you? For me it doesn't, only when running :Copilot, it shows 10 possible answers...

**Comment by haseeb-heaven** [comment]
You have to run command `Copilot setup` to set it up and then it will start running.

**Comment by alexbaikal** [comment]
I've set it up, had to paste this in nvim init.lua:
  vim.g.copilot_assume_mapped = true

**Comment by haseeb-heaven** [comment]
No i didnt had to do that step

**Comment by klcantrell** [comment]
> I've set it up, had to paste this in nvim init.lua:
> vim.g.copilot_assume_mapped = true

I needed this line as well otherwise no inline suggestions would show up. Just curious @alexbaikal, where did you find this setting? I'm not finding any documentation about it.

**Comment by feoh** [comment]
Hi guys! I just started using Copilot with Neovim myself, and I found what I see as a cleaner solution:

https://github.com/feoh/git_dotfiles/blob/master/.config/nvim/lua/custom/plugins/copilot.lua

Note that this also uses Ctrl-j as the "OK Copilot give me a suggestion" because I couldn't get copilot working with kickstart by default as copilot status would say that it's disabled by default since tab was already in use.

I suspect we could somehow integrate with cmp instead, but I'm happy to be explicit and use Ctrl-j when I want Copilot for now.

**Comment by catb0t** [comment]
> Note to user @haseeb-heaven i'm not 100% sure on this so someone correct me if i'm wrong. But i belive the reason that the method didnt work for both of us is due to the fact that kickstart uses the lazy plugin manager.
> 
> I was able to get copilot working on all my machines by going into my init.lua file and going to any location within the "require('lazy').setup({" bracket. And entering "'github/copilot.vim'," Heres a screenshot for reference. ![image](https://user-images.githubusercontent.com/66909997/219966405-c74d1ad5-d2a3-43f9-809b-0d9e07940ce4.png)
> 
> Try it out and see if the method works for you too.

Good tip. The install page doesn't mention that the command is targeting Packer etc.
