### ISSUE TITLE
Cannot configure rust-analyzer

### ISSUE THREAD

**Issue by matoushybl** [nvim-lua/kickstart.nvim#227]
Hi, I am using this config and I am trying to enable proc macro support, but I am not having any luck.
I modified the config's `servers` variable like this, but it seems like it never gets applied.
```
local servers = {
  -- clangd = {},
  -- gopls = {},
  -- pyright = {},
  rust_analyzer = {
    ["rust-analyzer"] = {
      cargo = {
      },
      procMacro = {
          enable = true,
      },
    }
  },
  -- tsserver = {},

  lua_ls = {
    Lua = {
      workspace = { checkThirdParty = false },
      telemetry = { enable = false },
    },
  },
}
```

I tried looking in the docs for mason-lspconfig, but it I wasn't able to find any relevant reason why this wouldn't work, other than there is a mistake in my configuration.

Sorry for asking here, I don't know a better place to ask.

Thanks!

**Comment by adilJamshad** [comment]
I am facing the same issue. Also, rust autocomplete isn't working for me

**Comment by feoh** [comment]
Folks I would suggest you try filing an issue on the [upstream repository](https://github.com/simrat39/rust-tools.nvim) because this seems like a problem with the rust-analyzer Neovim nubbins and not this config in particular.

Resolving this for now, please feel free to reopen if you feel there are config specific issues to be addressed here.
