### ISSUE TITLE
'help' -> 'vimdoc' in treesitter.

### ISSUE THREAD

**Issue by eyolf** [nvim-lua/kickstart.nvim#252]
On line 291 in init.lua, it says:

`   ensure_installed = { 'c', 'cpp', 'go', 'lua', 'python', 'rust', 'tsx', 'typescript', 'help', 'vim' }, `

but treesitter has changed 'help' to 'vimdoc'. With the current line, it produces an error. If 'help' is changed to 'vimdoc' it does not.

**Comment by thomasdohyunkim** [comment]
I'm running into the same issue right now as well.

**Comment by feoh** [comment]
Yup. I have a PR I made to fix this a few days back but I'm guessing the folks with the power to merge it have been too busy to look :)

https://github.com/nvim-lua/kickstart.nvim/pull/248

Go +1 / comment on it and maybe we can motivate some action :)

**Comment by rckwzrd** [comment]
I am getting the same error. Will swapping "help" for "vimdoc" fix the issue? Where is it stated that `treesitter` is switching to vimdoc?

**Comment by eyolf** [comment]
[Here, among other places:](https://github.com/nvim-treesitter/nvim-treesitter/commit/93fa5df0a3f0aeb72df50a9d2110cb90fc5a0a13)

And, yes, if you change that word in init.lua, it should work.

**Comment by craigmac** [comment]
@tjdevries the bigger issue here is the issue of kickstart.nvim saying it supports latest stable AND nightly. I think that should only target one or the other, because otherwise there's going to issues like this again and we probably don't want to have to have version checks and pcall() in places to make sure it works on nightly AND last stable release. 

Related  - by default Lazy does `version = false`, rather than `version = "*"` which tries to get last stable release. I can understand why it's done this way, but I digress.

**Comment by tjdevries** [comment]
Should be fixed now -- sorry for the delay
