### ISSUE TITLE
Autocomplete not showing up in my own scripts

### ISSUE THREAD

**Issue by ralfseduards** [nvim-lua/kickstart.nvim#268]
## Describe the bug
Kickstart autocomplete is working only when im editing the init.lua file, when im writing my own scripts, it is not showing up.

## To Reproduce
1. autocomplete works in .config/nvim but doesnt work when i go into my desktop folder

## Desktop
- OS: Macos
- Terminal: ITerm2

## Neovim Version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by zdebra** [comment]
Hello, I've just faced a similar issue. After a fresh install of nvim and applying this kickstart config autocomplete wasn't working. The issue is that only lua language autocomplete is installed after fresh install. 

How to fix this? Type `:Mason` as described in the [video](https://youtu.be/stqUbv-5u2s?t=370), find the language of your choice and install it with `i`. This worked for me (linux, nvim v0.9.0).

**Comment by feoh** [comment]
@ralfseduards What language are you hoping to auto-complete? As @zdebra says you need to install your LSP of choice using Mason.

Please feel free to re-open if you disagree or need more assistance after you've given us more details to go on.

**Comment by ralfseduards** [comment]
Thanks!🍻
