### ISSUE TITLE
Unable to change default options

### ISSUE THREAD

**Issue by ironhouzi** [nvim-lua/kickstart.nvim#300]
## Describe the bug

Not possible to change default configuration due to Lazy.nvim messing with rtp

## To Reproduce

1. Write file `~/.config/nvim/after/plugins/defaults.lua`: containing: `vim.o.clipboard = ''`.
2. Start nvim with `-V1` parameter: `nvim -V1`.
3. Run ex command: `:verb set clipboard?`.
4. Verify unchanged default value persists (`clipboard=unnamedplus`) and `Last set from ~/code/kickstart.nvim/init.lua line 207`.

## Desktop

- OS: Arch Linux
- Terminal: Alacritty

## Neovim Version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
After some investigation and help received from the NeoVIM Matrix channel, it seems like Lazy.nvim messes with the rtp. Which is also confirmed by a smattering of print lines, which reveals a trail showing that loading lazy.nvim triggers the evaluation of `~/.config/nvim/after/plugins/defaults.lua` prior to evaluating the remaining sections of `init.lua`.

I considered moving the lazy.nvim setup to the end of `init.lua`, but there's configuration of plugins in `init.lua` which defeats the purpose of being able to separate personal configuration with the default kickstart config, enabling clean merges of future commits.

**Comment by rodrigocam** [comment]
I have the same problem trying to remap telescope commands in my `after/plugins/defaults.lua`

**Comment by mech-a** [comment]
This is an interesting issue. Looking at the lazy.nvim startup sequence, all `after/plugin/*` files will be loaded at the end of the lazy.nvim invocation. However, since we have some overrides in `init.lua` afterwards, they get overridden. I initially thought this might be an issue with lazy.nvim; however, I feel that this makes sense as a default behavior. I have one solution in mind, but I'm still looking through dotfiles for some other ideas.

At the end of the kickstart init.lua, add a line to `require after`. the `after` directory is at `~/.config/nvim/lua/after` and there should be an `after/init.lua` where you can make adjustments to the default config. 

Personally, I am in favor of creating a folder `custom/config` instead of using `after` for consistency, but this is up to discussion.

**Comment by mech-a** [comment]
As a general observation, I'm seeing a misunderstanding for how to change options in kickstart. For changing the default options we have set, such as `mouse`, `clipboard`, and plugin configs like `treesitter`, it makes sense to change the  
kickstart init.lua to match your use case. Trying to change this by introducing a plugin configuration is not what users should do. If you create a plugin configuration only for setting up vim options like `mouse`, then it's a misuse of lazy.nvim, which is just to manage plugins. If you create a plugin configuration to further specify conflicting `treesitter` options, then naturally that will be overridden by `init.lua`. Users should edit the kickstart `init.lua` as needed to suit themselves; after all, it is just a template that is intended to be adjusted. Merge conflicts that may arise due to updating your local copy are just a byproduct of this project being a single-file config.

**Comment by feoh** [comment]
You're right. I think this is a mis-understanding, but I also get where it's coming from, both because I myself fall into it from time to time, and because we see it SO very often.

The nature of this project can create a bit of a conundrum for folks who are trying to come up to speed with all the technologies it encompasses.

Thanks very much for the reminder. @ironhouzi - can you please just go ahead and modify init.lua to suit your needs? I'm going to close this for now, and if you find more issues, please let us know.

@mech-a Do you think we should add something to the README or maybe the comments about this kind of thing? I know @tjdevries has bent over backwards trying to convince people PLEASE EDIT THIS TO SUIT YOUR NEEDS but (and I include myself in this!) we keep having this conversation so maybe we all need even more reminders? :)

**Comment by mech-a** [comment]
@feoh I have a few suggestions. I'll open a new issue for this.

**Comment by feoh** [comment]
@mech-a Don't want to give you more work, but for the same character count why not just do a PR for the README? :)

Hey, just really wanted to thank you for jumping in and helping so much with this project. It's a surprisingly tricky thing to maintain because everyone sees their own needs in it :)

If you ever make it to the Boston, Massachusetts, USA area I'd love to buy you a beverage :)

**Comment by mech-a** [comment]
Good point about the PR. I'll do that instead.

Glad to be able to help -- definitely seems tricky to balance being a template and maintaining _just enough_ functionality. Will be collaborating more!

Will reach out if I'm in Boston for that drink :)
