### ISSUE TITLE
Kickstart in the Lazyman Neovim Configuration Manager

### ISSUE THREAD

**Issue by doctorfree** [nvim-lua/kickstart.nvim#308]
I've created a Neovim Configuration Manager that supports easy installation and initialization of multiple Neovim configurations using the `NVIM_APPNAME` environment variable in Neovim 0.9.  I call it Lazyman and include support for `Kickstart` as one of the "Starter" Neovim configurations installed and initialized by `lazyman`.

See https://github.com/doctorfree/nvim-lazyman for info on Lazyman.

I'm contacting the maintainers of the Lazyman supported Neovim configurations to seek any feedback on the description, installation, and initialization of their config in Lazyman. Please feel free to let me know what I'm doing wrong or how I could improve the incorporation of `Kickstart` in Lazyman. If you feel there is a need to modify the way `Kickstart` is used in Lazyman then open an issue at https://github.com/doctorfree/nvim-lazyman/issues

This isn't really an issue with Kickstart, it is just a heads up and request for feedback.

Kickstart is very cool. Thanks!

**Comment by feoh** [comment]
Hiya! Thanks for filing this issue. This looks like a neat project!

Since it doesn't seem like you have any asks for us, I'm going to close it for now.

The only feedback I have is that I'm a bit concerned that new Neovimmers might actually not be well served by the additional complexity lazyman brings to the table, but other than that it's a great idea for certain use cases and a very cool project!

**Comment by doctorfree** [comment]
@feoh thank you for responding and the feedback. Yes, I agree, the additional complexity required to support dozens of configurations in a single command is possibly the largest drawback. I've tried to make it as simple as possible but there are no doubt improvements that could be made to ease use. I would welcome any suggestions with regards reducing complexity. Or, any other comments you might have. Thanks!
