### ISSUE TITLE
Autocomplete not working on Debian 11 and nvim.appimage v0.9.1

### ISSUE THREAD

**Issue by tonny-sofijan** [nvim-lua/kickstart.nvim#370]
## Describe the bug
Autocomplete not working on Debian 11 and nvim.appimage v0.9.1. I've tried on 2 debian 11 installation and it doesn't work.

## To Reproduce
1. apt-get install nodejs, npm, gcc, build-essential, python3-pip.
2. Download nvim.appimage v.0.9.1, create link in /bin.
3. Get kickstart.nvim code from here.
4. Run nvim
5. Run :MasonInstall intelephense.
6. Open my php file, type what's on 1 line above, ..
7. But no autocomplete, at all.

## Desktop
- OS: Debian 11
- Terminal: SSH-ing, with /bin/bash

## Neovim Version
NVIM v0.9.1
```
```

**Comment by feoh** [comment]
Hi!

I'm sorry you're having trouble, however the problem you cite is with the PHP language server specifically. Please report an issue on [their repo](https://github.com/bmewburn/vscode-intelephense).

I note that while it being an LSP it *should* be possible to get PHP autocomplete working with this tool, a quick google reveals many forum posts asking the same question.

I'm closing this because it's not actually a kickstart.nvim issue - Thanks for the report and good luck!

**Comment by tonny-sofijan** [comment]
Thanks for the answers, I've got it working on debian 11. The problem is not with the PHP language server, but the nodejs and npm packages. When I use newest node packages (node v20.5.0, npm v9.8.0), everything work as intended. 

Thanks again for this useful project! :)
