### ISSUE TITLE
Post Installation… huh?

### ISSUE THREAD

**Issue by michaelGregoire** [nvim-lua/kickstart.nvim#478]
Please simply explain in the README what the "Post Installation" command `nvim --headless "+Lazy! sync" +qa` is actually doing and why it's needed. **kickstart.nvim** is seemingly geared toward making it easier for folks to approach neovim, so please explain things to us like we’re 5. We want to learn. K thanx bye.

**Comment by dam9000** [comment]
That is supposed to install the configured plugins.
Here is what the individual options do:
  `--headless`: run without a UI, just execute the provided commands
  `"+Lazy! sync"`: Run install, clean and update the plugins
  `+qa`: quit

However, the funny thing is, Lazy sync is run automatically on the first run by the Lazy manager anyway. If you just run nvim without arguments on a fresh install you will see the Lazy plugin manager doing it's thing - installing and synchronizing the plugins.

In addition the `"+Lazy! sync"` is not even recognized as a valid command, perhaps because the Lazy plugin manager was not yet loaded at the time the nvim tries to execute the command line commands, perhaps it executes them before loading the init.lua.

Here is what you get without the `--headless` and `+qa` commands, that will allow you to see the output:

```
Error detected while processing command line:
E492: Not an editor command: Lazy! sync
Press ENTER or type command to continue
```

So it seems the instruction should actually be to just run:
`nvim --headless +qa`
Which would perform the first-time install of plugins.

Or perhaps better, just run nvim without arguments, so that you can see what is actually going on. With the readme saying that on the first run the plugins will be installed, perhaps that would be more instructional.

**Comment by michaelGregoire** [comment]
Thanks for the detailed response. Much appreciated! That explains why the couple videos I've seen only say that you need to grab the `init.lua` to install.

**Comment by feoh** [comment]
@michaelGregoire That's a different problem :( Those videos are out of date and wrong. I won't ask the authors to update them because it's a lot of work but I would love it if they did :)

If anyone wants to generate a PR to update the README.md removing the options so foks just get to invoke Neovim normally and watch the update/install, I'm totally fine with that and would gladly merge it.

**Comment by dam9000** [comment]
For completeness, as I was wondering why without headless sync didn't work here is the answer, for the interested:
https://github.com/folke/lazy.nvim/issues/285#issuecomment-1568456990

**Comment by dam9000** [comment]
Anyway here is a PR with a change to the README:
https://github.com/nvim-lua/kickstart.nvim/pull/479

Perhaps now it is too verbose? Let me know if you would prefer to word it differently.

**Comment by feoh** [comment]
Love it! Merged it! Thanks for your help. Closing.
