### ISSUE TITLE
Colour problem

### ISSUE THREAD

**Issue by UpatronoL** [nvim-lua/kickstart.nvim#510]
## Describe the bug

I am currently having a bug with the color scheme when I am running nvim using kickstart

## To Reproduce

1. the colour scheme instead of looking nice its looks all blue and I don't know how to change it

## Desktop

- OS: macOS
- Terminal: zsh

## Neovim Version

I have the latest version of nvim which is 0.9.4

**Comment by kensonjohnson** [comment]
This is because the default terminal in MacOS (terminal.app) doesn't support truecolor, even though zsh does. The simplest solution is to use a different terminal emulator. I use [iterm2](https://iterm2.com/) for MacOS, which does support truecolor. The other option is to change the theme to one that can use the 256 color scheme.

**Comment by feoh** [comment]
Please use a terminal that supports 256 colors like [iTerm2](https://iterm2.com/) [Alacritty](https://github.com/alacritty/alacritty) or [Kitty](https://sw.kovidgoyal.net/kitty/).

**Comment by ajmichels** [comment]
This one tripped me up as well. Perhaps adding a note about this to the Readme would be a good idea. I think there are probably a lot more people using the default terminal on MacOS than one might realize.

Also, it seems like if the goal of this project is to lower the barrier of entry for users new to Neovim then using a theme that doesn't require truecolor would be a good idea. :shrug: Maybe the issue goes beyond just the theme, either way it is unfortunately. Ideally Apple would update their software but ...
