### ISSUE TITLE
Proposal for using Github actions

### ISSUE THREAD

**Issue by juangiordana** [nvim-lua/kickstart.nvim#515]
Hello,

I'm following this repo in order to keep track of the changes made to the repo and incorporate them into my now grown config.

Most of the notifications I receive are from people trying to push changes into their own forks. Usually newcomers finding their way through git.

I'm using NixOS since a few months now, so my setup is kind of different for this OS, but I like the "do not fork" principle of this project: https://github.com/mrcjkb/kickstart-nix.nvim 

I think it uses GitHub actions to encourage people to create their own fork and I think this would help a lot reduce the noise in the project.

Any thoughts?

**Comment by feoh** [comment]
This sounds great! Unfortunately I can't see any Github actions control files on that repository, but maybe I'm not sure where to look?

Why not just generate a pull request?

**Comment by mrcjkb** [comment]
Hey :)

Here's how you set up a template repository 😄 

Repo settings -> General

![IMG_20231209_101325](https://github.com/nvim-lua/kickstart.nvim/assets/12857160/60f15cfd-519a-4aba-8f78-a9a6362ab22e)

**Comment by dam9000** [comment]
I guess it wouldn't hurt enabling the template flag. From what I could gather, this does not prevent one from directly cloning and forking as is, but it adds a button `use this template` near the fork button, as can be seen for example here:
https://github.com/sindresorhus/electron-boilerplate
Using a template has it's drawbacks though, it will create a new repo with just a single squashed commit with the last state of the repo and it will not have any common history with the repo, true this prevents one from creating pull requests, but it also prevents one from pulling in new changes in case one wants to keep in sync with the new upstream fixes and improvements. So if this is enabled perhaps a note should be added to the README of what are the available options and differences between them. (clone, fork, template).

I think there is also a fourth option and that is to lock the master branch for all except admins and create a contrib branch. The default branch would remain master, so it would prevent accidental pull requests, but allow people to sync with upstream. The contrib branch would be available to make pull requests against it, as one would need to switch the branch before making a PR I think this would prevent opening accidental PRs. This would add an additional overhead to the admins though, once the PR is merged to contrib, the admin will need to sync up also master, preferably using a fast-forward merge so that master and contrib end up pointing to the same commit.

@feoh are you interested in setting up anything of the above?

**Comment by mrcjkb** [comment]
With a template, there's no `sync fork` button, but you can fetch upstream fixes and improvements by adding it as a remote:

```console
git remote add upstream git@github.com:nvim-lua/kickstart.nvim.git
```

Then, to fetch and merge changes:

```console
git fetch upstream
git merge upstream/master --allow-unrelated-histories
```

**Comment by feoh** [comment]
respectfully, I don't think the template idea is actually going to help and will create problems of its own.

As @dam9000 said, I think that we need to lock the master branch if we actually want to solve this problem.

I know we get email, but I don't have strong enough feelings on this topic to go ahead and implement it.


also, I am a collaborator, and I don't think I have the permissions anyway. Folks will need to petition the actual owners of this repository in order to make this happen. 

as for myself, I will just continue to delete the emails and shrug :-)
