### ISSUE TITLE
Error report after initially executing init.lua on starting nvim

### ISSUE THREAD

**Issue by b9Joker108** [nvim-lua/kickstart.nvim#557]
## Describe the bug
Error report after initially executing init.lua on starting nvim

## To Reproduce
1. I was following along with this YouTube video: https://youtu.be/stqUbv-5u2s?si=M1PuANMGG9FPxtaW
2. I created a nvim directory in ~/.config
3. I copied the text in GitHub: init.lua
4. I pasted the contents in a new textfile called init.lua in the nvim directory 
5. I saved and exited
6. I exited shell session
7. I started a new shell session
8. I ran: nvim
9. nvim executed init.lua
10. Plugins started installing
11. I got an error that some 'translation' file couldn't install
12. I got a shell error output, please refer pastebin link: https://pastebin.com/Hp6Ks7Ym
13. Any assistance would be appreciated
## Desktop
- Tablet: Samsung Galaxy Tab S9 Ultra (SM-X910)
- OS: OneUI (v. 5.1.1: Android 13)
- Terminal: Termux (v. 0.118.0)

## Neovim Version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by dam9000** [comment]
The log you posted says:
```
[mason-lspconfig.nvim] failed to install lua_ls. Installation logs are available in :Mason and :MasonLog
```
it would be helpful to provide also the output of `:MasonLog`

Anyway, the issue is that lua_ls is not supported on Android.
This seems to be a duplicate of: https://github.com/nvim-lua/kickstart.nvim/issues/214
Also reported in mason repo: https://github.com/williamboman/mason.nvim/issues/306

According to the comments in the above tickets, you could either try to install lua_ls on android manually, or if you don't need it, you can disable it by commenting out or deleting it from the mason config, here:
https://github.com/nvim-lua/kickstart.nvim/blob/4d0dc8d4b1bd6b94e59f7773158149bb1b0ee5be/init.lua#L573
You can use `--[[` `--]]` to comment out a block of code.

**Comment by b9Joker108** [comment]
Thank you so much, that worked. The error output has gone quiet.

**Comment by b9Joker108** [comment]
I closed this case as issue, resolved.
