### ISSUE TITLE
Custom settings

### ISSUE THREAD

**Issue by trevg22** [nvim-lua/kickstart.nvim#574]
Hey this project is absolutely amazing and I have been loving using it, unfortunately I find myself fairly regularly resolving merge conflicts in my fork, for changes for I have made in the init.lua. Is there a way where I could say append or override to servers={}  array in a file that would not create conflicts such as lua/custom/settings.lua. Basically just some overrides that do not collide with the great changes people are pushing? This is being done with the plugins so was hoping there is something similar, if there is a solution I dont mind adding to readme.
Thanks!

**Comment by feoh** [comment]
Hiya!

I feel your pain, and I've been through this before myself.

This may be an unpopular opinion, but given that you're just maintaining a downstream fork like I am, I fixed this by simply running `git merge upstream/master` rather than trying to rebase.

If I rebased, I found I had to re-litigate EVERY SINGLE CONFLICT EVER and when I just started merging down to my fork, all that went away. 


Hope this helps!

**Comment by SiddharthPant** [comment]
Another way that I do in my fork is to create a "my-master" branch that I use as my working branch and keep the master branch always in sync with upstream. Till now I have not made that many changes that have caused conflicts so for me rebase still works but yeah if I start facing conflicts I will also start using merge like @feoh

**Comment by trevg22** [comment]
Thanks guys! I think eventually it would be nice to have custom settings files if others would like them as well, I will do some thinking on that. For the meantime I think I am going to use both of your methods in tandem.

**Comment by bbaldino** [comment]
I took @feoh 's advice and did make a fork, but I've been trying to keep as many of my changes as possible outside the main config to avoid conflicts because I'm planning on trying to rebase as well.  One of the changes I made was [adding support for loading a file outside of init.nvim file with tweaks in it](https://github.com/bbaldino/kickstart.nvim/commit/3435ce8dc3c11303a484abb9c07be3c236d23aa7).  The custom plugins hook works fine for plugins, but not for other tweaks.  Today I ran into a need to be able to have some logic in `onattach` (to detect and enable inlay hints if they're available) which will require another hook in `init.lua` I think, but at least it keeps the changes in `init.lua` small.  I do feel like it'd be nice for kickstart to include these hooks--I get the intent is for people to take it and make it their own, but there's too much good stuff here not to want to get all the updates :)

**Comment by feoh** [comment]
You don't need to avoid changing the actual init.lua code - and in fact in many cases you *can't* without substantially modifying kickstart.

As I've previously said:

1) Unless you like pain, don't rebase, just merge.
2) Go ahead and modify things. As Teej says repeatedly, this is YOUR config! kickstart is meant as a launchpad to get you going :)

I've been keeping [my fork](https://github.com/feoh/kickstart.nvim) 100% up to date with the main nvim-lua/kickstart.nvim repository with zero effort despite making substantial changes including:

- A totally different color scheme (I'm partially blind and onedark literally gives me a severe headache)
- Many additional plugins and their configurations like neotree, debugging additions, smartyank. The list goes on :)

I know this stuff is a bit of a faff but it's entirely possible. If anyone needs detail level help just ask and I'll do what I can!

I'm closing this for now because I feel like we've been over this a bunch. If folks have README changes they feel would help folks get their heads around this stuff please do feel free topen a PR!
