### ISSUE TITLE
Handle `GIT_DIR` and `GIT_WORK_TREE` being set when cloning.

### ISSUE THREAD

**Issue by ahmedcharles** [nvim-lua/kickstart.nvim#798]
Due to how I track my dot files, I ended up with `GIT_DIR` and `GIT_WORK_TREE` set when running `nvim` for the first time.

I would submit a PR to fix it instead, but I'm not sure whether the desired approach here is to:

1. Do nothing. :)
2. Detect that they are set and fail with an error.
3. Detect that they are set and unset them.

## Describe the bug
The git command to clone the lazy repo fails.

## To Reproduce
1. Set `GIT_DIR` and `GIT_WORK_TREE` to something reasonable.
4. Open `nvim` for the first time.

## Desktop
- OS: Linux
- Terminal: gnome-terminal

## Neovim Version

```
:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by dam9000** [comment]
In my view this is a very specific issue related to your environment which you will need to be mindful of. I don't expect it would be common to have these env vars set this way. So I think there is nothing that needs to be done. You can however try unsetting these vars in your own init.lua, although that would probably mean that gitsigns won't work with your git files. On the other hand it's clear that setting GIT_DIR is not compatible with the way the nvim plugins work - which is by cloning various git repos, so that's where it conflicts.

**Comment by feoh** [comment]
Hi. Thanks for the report.

As @dam9000 indicated this is an aspect of your Git environment that kickstart really has no truck with and *definitely* shouldn't alter.

You could always create an alias to invoke Neovim with something like: `alias nvim='export GIT_WORK_TREE="";export GIT_DIR="";nvim`.

So, this isn't a kickstart bug and I'm closing for now.
