### ISSUE TITLE
Debian install procedure has you changing the entire distribution to unstable to install Neovim

### ISSUE THREAD

**Issue by EvanCarroll** [nvim-lua/kickstart.nvim#859]
Currently the [documentation for Debian](https://github.com/nvim-lua/kickstart.nvim/blame/master/README.md#L196) instructs you to do this,

```sh
sudo apt update
sudo apt install make gcc ripgrep unzip git
echo "deb https://deb.debian.org/debian unstable main" | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install -t unstable neovim
```

The problem is this line,

```
echo "deb https://deb.debian.org/debian unstable main" | sudo tee -a /etc/apt/sources.list
```

That effectively moves you to the unstable version of debian. If you run `apt-get dist-upgrade` and download all of your packages, and then you run the above code and you rerun `apt-get dist-upgrade` you will be on the unstable version of Debian.

This is probably not what you want.

The problem that you're trying to solve is that Debian stable (right now "bookworm") ships Neovim 0.7.2. Unfortunately, there is no newer version of Neovim in the repository, nor in the backports repository (because of a shortage of manpower). However, upgrading your entire distribution to unstable is a very poor suggestion that can cause all kinds of problems and pain, including total failure.

**At the very least, the user should be informed**

**Comment by EvanCarroll** [comment]
This edit was done last month by @dam9000 https://github.com/nvim-lua/kickstart.nvim/commit/a222805c6120b88f451c3e026b29ea6f761a491e

A better way for the Linux's is probably just to use upstream neovim's prebundled binary if that works for you, https://github.com/neovim/neovim/blob/master/INSTALL.md#pre-built-archives-2

**Comment by feoh** [comment]
@EvanCarroll I see what you mean.

As an interim step, would you or anyone commenting here please consider updating the verbiage in the install instructions to warn appropriately?

A problem I see is that in order to update Debian to the point where you can *build* Neovim, you kind of have to go unstable.

Perhaps simply stating that up front and offering the pre-built binary as an alternative is the way to go here? I'll leave it to the Debian folks to craft an appropriate and best practice conformant set of install instructions.

**Comment by EvanCarroll** [comment]
> A problem I see is that in order to update Debian to the point where you can build Neovim, you kind of have to go unstable.

I don't believe this is true. I don't know why specifically you couldn't build Neovim 0.9 on Debian stable (bookworm).

> Debian folks to craft an appropriate and best practice

I would use either the binaries from neovim, or flatpak. Or we could beg the Debian maintainer to onboard me, and I'll personally start rolling out backports for stable. But I don't think he'd be down.

**Comment by feoh** [comment]
No one is asking you to take over Maintainersship of a package. All I'm suggesting is that since you were kind enough to point out problems with our documentation as it currently stands and since most of us do not run Debian, perhaps you would consider crafting alternative text that does not violate best practices.

**Comment by dam9000** [comment]
@EvanCarroll I'm sorry about the confusion I caused with this. I'm not a regular debian user so I was going from various guides on the net and was under impression that the unstable repo will be used only if the `-t unstable` parameter was provided, perhaps that is not the true so indeed this needs to be corrected.
