### ISSUE TITLE
How can I idiomatically add a language server if it's not supported by Mason?

### ISSUE THREAD

**Issue by yehorh** [nvim-lua/kickstart.nvim#889]
For example, dartls isn't supported by Mason, but it is already supplied with Dart. I know I can add it to the end of the config file:
```lua
require('lspconfig').dartls.setup {}
```
But I don't want fragmentate configuration file.
However, I don't want to fragment the configuration file.

**Comment by feoh** [comment]
Hi!

First, you're going to need to be willing to write and debug some configuration code on your own because you're choosing to color outside the lines.

That said, kickstart uses lspconfig so I wonder if you could easily adapt this [snippet](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/dartls.lua).

**Comment by feoh** [comment]
You might also find [this closed issue](https://github.com/williamboman/mason.nvim/issues/156) on the Mason repo helpful.

**Comment by feoh** [comment]
Anyway, this isn't actually an issue with Kickstart. Hope these resources help! Going to close this for now. Thanks for you contribution!
