### ISSUE TITLE
Newb question: Where do I file a bug for the autocomplete for CSS files?

### ISSUE THREAD

**Issue by genericrohan** [nvim-lua/kickstart.nvim#897]
Hi, I'm new to coding and just learning nvim because I hate making progress in my life and prefer side-quests instead, apparently. Anyway...

I am using nvim w/ kickstart's config to edit a `.css` file and when I try to write css for the `*` selector, the...autocomplete...thing (idk what it's called) seems to treat it as a multi-line comment. What I mean is, if I start with:
```css
* {}
```
and then press `<Enter>` with my cursor between the braces, I end up with:
```css
* {
        * 
* }
```
instead of 
```css
* {
   
}
```

![image](https://github.com/nvim-lua/kickstart.nvim/assets/129636054/ce12cca8-00eb-42ef-b3ca-007ff6236ed2)

I know it's probably some plugin or something that does this, but I'm not sure which one or which one I should file the actual bug report with. I asked ChatGPT and it said that tree-sitter-css is only for syntax highlighting and since it's the only css thing I remember installing during the setup of neovim, I'm not sure what else to look for.

If someone can point me in the right direction, that would be appreciated.

**Comment by dam9000** [comment]
Treesitter taks care of: highlighting, indenting, incremental selection. Any of these can be disabled with `:TSDisable`:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/a9629ea3-17b4-474f-a04b-526cc5dca365)
However, the behaviour you described is not caused by Treesitter, I tried running plain nvim without any plugins `nvim --clean` and it behaves the same, so it must be caused by some built-in rules. I was not able to disable this and I tried:
`:set nocindent`
`:set noautoindent`
`:set nosmartindent`
See: `:help indent` for more info about the above (https://neovim.io/doc/user/indent.html)
Sorry I don't have a solution, just some additional info for context.
Perhaps someone else will be able to answer this.

**Comment by dam9000** [comment]
I went digging around the nvim runtime files for css:
```
/usr/share/nvim/runtime/indent/css.vim
/usr/share/nvim/runtime/ftplugin/css.vim
/usr/share/nvim/runtime/ftplugin/css.lua
/usr/share/nvim/runtime/syntax/css.vim
```
And found these additional options:
```
setlocal omnifunc=csscomplete#CompleteCSS
setlocal indentexpr=GetCSSIndent()
```
However, what is causing the described behaviour is:
```
setlocal comments=s1:/*,mb:*,ex:*/ commentstring&
```
And can be disabled with:
```
:set comments=
```
This should probably be refined further, but I guess it's a starting point.

**Comment by feoh** [comment]
@dam9000 Thanks a bunch for digging in!

In any case,  please feel free to file a bug against [the main Neovim repo](https://github.com/neovim/neovim) for runtime improvements. This isn't a kickstart issue.
