### ISSUE TITLE
Isn’t `hlsearch` the default option? I’m missing something?

### ISSUE THREAD

**Issue by brxxlstxrs** [nvim-lua/kickstart.nvim#941]
And why is that necessary?
https://github.com/nvim-lua/kickstart.nvim/blob/5aeddfdd5d0308506ec63b0e4f8de33e2a39355f/init.lua#L161

**Comment by feoh** [comment]
Kickstart is a set of opinionated defaults. You're free to fork and modify to your heart's content.

**Comment by rmacklin** [comment]
I think they were asking if that line should be removed, not because they disagree with it, but because it appears to be set to the value that neovim defaults to.

**Comment by rmacklin** [comment]
Looks like it has been the default since 2015: https://github.com/neovim/neovim/commit/9ebb5c681b92c3c26171aa5514cd18a17dd62bad so it probably is safe to remove. But also note the comment above that line is actually describing both that line and the subsequent line:
https://github.com/nvim-lua/kickstart.nvim/blob/6f3fe35de355b71257fe987537727ca2c7101c0c/init.lua#L160-L162

If line 161 is removed, that comment becomes a bit more ambiguous. If you come up with an appropriate rewording of the comment with line 161 removed, you could open a PR.

**Comment by feoh** [comment]
looks like I close this one error. I'll reopen it and please feel free to file a PR.
